### ISSUE TITLE
Fix and deploy web application

### ISSUE THREAD

**Issue by varchanaiyer** [saimani-18/insights_generation_#1]
![image](https://github.com/user-attachments/assets/6f12410b-e516-4a0d-aebb-198e8ced8824)

The web application at insightgenerator.pythonanywhere.com is currently not accessible. Debug, fix, and redeploy the application to ensure it's functional and accessible to users

**Comment by saimani-18** [comment]
![Screenshot 2024-08-11 123557](https://github.com/user-attachments/assets/609106e6-58a8-47ca-8fd5-d0346dc094fd)

I apologize for any inconvenience caused by the  app exception. It was our oversight not to clarify the file requirements earlier.

To ensure smooth functionality, please use only well-structured CSV files that can be easily opened in Excel. Unfortunately, text-based CSVs with irregular or unstructured data are not supported. Additionally, due to limitations of the free domain space, we are restricted from further enhancing insight generation at this time.

I wanted to let you know that I have rechecked the application, and it is functioning smoothly on both mobile and laptop devices. I did not encounter any issues during my tests.

If possible, could you please try running it in Google Chrome to see if the problem persists on your end?

https://insightgenerator.pythonanywhere.com/
